services:
  handshaked:
    # DO NOT USE THIS IMAGE EXCEPT FOR TESTING!
    image: ghcr.io/handshake-org/hsd:latest
    command:
      - hsd
      - --network=main
      - --http-host=0.0.0.0
      - --api-key=foo

  exporter:
    image: handshake-prometheus-exporter:latest
    build: .
    ports:
      - "12000:12000"
    environment:
      HANDSHAKE_RPC_HOST: handshaked
      HANDSHAKE_RPC_USER: "x"
      HANDSHAKE_RPC_PASSWORD: "foo"
      REFRESH_SECONDS: 1
      BAN_ADDRESS_METRICS: true
      LOG_LEVEL: "INFO"
    depends_on:
      - handshaked
    #volumes:
    # For explicit config file path (with BITCOIN_CONF_PATH above).
    # - ./test-bitcoin.conf:/etc/bitcoin/bitcoin.conf
    # For default bitcoin config location (nobody user).
    # - ./test-bitcoin.conf:/.bitcoin/bitcoin.conf
